### ISSUE TITLE
Update package.json to allow minor version differences

### ISSUE THREAD

**Issue by BrycenDavisSH** [tonysamperi/ngx-popperjs#11]
**NOTE**

**Describe the bug**
If this is not a valid request, please feel free to delete. This package should try to do angular references / peer dependencies using the '^' vs '~'. This would allow me to use the latest version 12.2.0. Right now it only allows up to 12.1.3. It would also cut down on the updates from your side as anything in the 12.1.3 >= version < 13 would work on my side.

**Comment by tonysamperi** [comment]
Actually I think you're right. I don't know why I believed it was better to verify compatibility, but as stated [here](https://angular.io/guide/releases)

> Minor releases contain new smaller features. Minor releases are fully backward-compatible; no developer assistance is expected during update, but you can optionally modify your applications and libraries to begin using new APIs, features, and capabilities that were added in the release. We update peer dependencies in minor versions by expanding the supported versions, but we do not require projects to update these dependencies.

So I guess I can definitely swap those tildes with carets.
If you want to do a pull request we could speed-up the change.

Thanks for reporting.
