### ISSUE TITLE
On touch devices scroll closes popup

### ISSUE THREAD

**Issue by berkayyildiz** [tonysamperi/ngx-popperjs#18]
**Describe the bug**
On touch devices scroll closes popup

**To Reproduce**
Add click trigger and closeOnClickOutside attribute to popup. Open on a mobile device and scroll with touch.

**Expected behavior**
Popup should remain.

**Additional context**
I checked old repo and to get click events on some mobile devices `this._globalEventListeners.push(this._renderer.listen("document", "touchend", this.hideOnClickOutsideHandler.bind(this)));`code added to `popper.directive.ts`. But this cause a scroll as click outside.

[Similar bug issue on old repo](https://github.com/MrFrankel/ngx-popper/issues/113)
[The issue that caused the error on old repo](https://github.com/MrFrankel/ngx-popper/issues/73)

**Comment by tonysamperi** [comment]
Absolutely not true. Just checked. Try on the demo page.

**Comment by berkayyildiz** [comment]
There is not an example that use hideOnClickOutside on demo page. 

Can you check this example [https://angular-ivy-awfugd.stackblitz.io](https://angular-ivy-awfugd.stackblitz.io)? Open the poppover and scroll with touch. Poppover should not close when user just scroll, it should close on click outside.

Editor Link
https://stackblitz.com/edit/angular-ivy-awfugd

**Comment by tonysamperi** [comment]
@berkayyildiz it seems that to fix what you say we should revert this commit.

https://github.com/MrFrankel/ngx-popper/commit/96edf1af751e79de2c13888bd3dd935c14d4b30f

I'll do some tests. I'm locking comments anyway. I will tag you when I have news.
Cheers and thanks for reporting.

**Comment by tonysamperi** [comment]
Fixed in v 13.0.1
