### ISSUE TITLE
ng update -> Angular 10

### ISSUE THREAD

**Issue by creffect** [tonysamperi/ngx-popperjs#2]
Dear tonysamperi,

thanks for continuing to maintain this library for Angular 10+

I tried to use ng update from Angular 9, but I get this error:

`Package "ngx-popperjs" has an incompatible peer dependency to "@angular/common" (requires "^8.2.14" (extended), would install "10.2.4").`

Maybe you could update the compatible package versions for angular 10. Thank you! :)

**Comment by tonysamperi** [comment]
Hello, 
the update for Angular 10 is in progress, but as you may understand I work on this stuff on my spare time, so I can't say for sure when it will be out.
I'll leave this issue opened till I publish the update, so you'll know when it's out!

**Comment by tonysamperi** [comment]
Updated to Angular 10! Enjoy!
