### ISSUE TITLE
I am too incompetent for this world

### ISSUE THREAD

**Issue by TC131425** [tonysamperi/ngx-popperjs#22]
Hello all,
I came across this project today because a colleague at work recommended Popperjs to me. Since I work with Angular I tried to use your wrapper. 
I am working with Angular version 13.2.0.
After some testing, unfortunately, the only thing left for me to do is to annoy you with my inability.

My questions would be:
Where do I find the SystemJS file in an Angular 13 project? 
How do I include your stylesheets in the project? I tried it via the Styles.css. Unfortunately unsuccessfully.
Could you maybe provide a simple example in stackblitz or something similar?
At the Moment my Popper looks like this:

![grafik](https://user-images.githubusercontent.com/96053268/156426231-1f8b04d4-b881-4f47-be82-b269a5e98838.png)

Many greetings.

**Comment by tonysamperi** [comment]
Pal, you clearly misunderstand the sense of an open-source project.

Good luck.
