### ISSUE TITLE
Types are not assignable to defined types

### ISSUE THREAD

**Issue by KenGuggelmeyer** [tonysamperi/ngx-popperjs#23]
Hi,

I'm getting errors on all of the binded properties. E.g.: popperPlacement.

I've installed this package with the following command:

`npm install @popperjs/core ngx-popperjs --save`

I then added the NgxPopperjsModule to the import section of my Module:

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { EmployeesRoutingModule } from './employees-routing.module';
import { IndexComponent } from './index/index.component';
import { LayoutModule } from '../layout/layout.module';
import { SharedModule } from '../shared/shared.module';
import { ShowComponent } from './show/show.component';
import { EditComponent } from './edit/edit.component';
import { NgxPermissionsModule } from 'ngx-permissions';
import { PermissionsComponent } from './edit/permissions/permissions.component';
import { NgxPopperjsModule } from 'ngx-popperjs';



@NgModule({
  declarations: [
    IndexComponent,
    ShowComponent,
    EditComponent,
    PermissionsComponent
  ],
  imports: [
    CommonModule,
    EmployeesRoutingModule,
    LayoutModule,
    SharedModule,
    NgxPermissionsModule.forChild(),
    NgxPopperjsModule
  ],
})
export class EmployeesModule { }
```

I then included an example from your page into my component html:

```
<popper-content #popper1Content>
    <p class="bold">Popper on bottom</p>
</popper-content>
<div [popper]="popper1Content" [popperShowOnStart]="true" [popperTrigger]="'click'" [popperHideOnClickOutside]="true"
    [popperHideOnScroll]="true" [popperPlacement]="'top'">
    <p class="bold">Hey!</p>
    <p class="thin">Choose where to put your popper!</p>
</div>
```

Angular then just refuses to build citing the following errors (I've omitted the locations of the files for the sake of clarity):

```
Error:  error TS2322: Type '"click"' is not assignable to type 'NgxPopperjsTriggers | undefined'.

70 <div [popper]="popper1Content" [popperShowOnStart]="true" [popperTrigger]="'click'" [popperHideOnClickOutside]="true"
                                                              ~~~~~~~~~~~~~



Error: error TS2322: Type '"top"' is not assignable to type 'NgxPopperjsPlacements'.

71     [popperHideOnScroll]="true" [popperPlacement]="'top'">
                                    ~~~~~~~~~~~~~~~ 
```

When i delete these properties, the popover is showing.

This is on my Desktop running the following:
OS: Windows 11
Browser: Microsoft Edge - 101.0.1210.47
Angular: 
`Angular CLI: 13.3.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.3.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@schematics/angular             13.3.5
rxjs                            7.5.5
typescript                      4.6.4`

**Comment by tonysamperi** [comment]
Do you think it would be possible to publish a library with such a bug?
You should deep dive Angular documentation.
I'll give you a hint: popperTrigger and most of the other input properties are Enums.

Cheers

**Comment by tomer953** [comment]
Hi,

**From where to import the Enum?**

in my component:
```
import { NgxPopperjsTriggers } from 'ngx-popperjs/public-api';
.
.
.
export class AppComponent {
    NgxPopperjsTriggers = NgxPopperjsTriggers;
```

`Error in ...... Module not found: Error: Package path ./public-api is not exported from package \node_modules\ngx-popperjs (see exports field in \ngx-popperjs\package.json`

also tried to import via different paths, no success.

```
angular: 13.3.2
ngx-popperjs: 13.1.0
```
