### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by kKen94** [tonysamperi/ngx-popperjs#25]

**Comment by tonysamperi** [comment]
@kKen94 hai letto il readme?

**Comment by kKen94** [comment]
> @kKen94 hai letto il readme?

Guarda scusami tanto, da programmatore ho filtrato tutto il pippone guardando se ci fosse un "14" sia nel readme che nelle recenti commit

**Comment by tonysamperi** [comment]
@kKen94 ok! Comunque ci sto lavorando, ho dovuto aggiornare delle dipendenze sotto ad Angular 14.
Ci vorrà ancora qualche giorno ma arriva anche questa...

**Comment by kKen94** [comment]
> @kKen94 ok! Comunque ci sto lavorando, ho dovuto aggiornare delle dipendenze sotto ad Angular 14.
> Ci vorrà ancora qualche giorno ma arriva anche questa...

Perfetto grazie, è che mi manca solo la tua e non posso cambiarla perché sinceramente è fatta superbamente, però vedendo quanto sei presente nessun problema. A volte c'è la paura dell'abbandono:D

**Comment by tonysamperi** [comment]
@kKen94 ahahah ti capisco benissimo, indovina perché ho preso in mano questo progetto 😂😂😂
