### ISSUE TITLE
BUG: Cannot find module '@ngx-tonysamperi/dom'

### ISSUE THREAD

**Issue by habtim** [tonysamperi/ngx-popperjs#26]
**Describe the bug**
When using this library, by `npm install @popperjs/core ngx-popperjs --save`, `@ngx-tonysamperi/dom` is not installed as it is not marked as a peer dependency. 
Therefore, I get an error when consuming `NgxPopperjsModule`:
```
Cannot find module '@ngx-tonysamperi/dom' from '../../../../node_modules/ngx-popperjs/fesm2020/ngx-popperjs.mjs'
```

**Workaround:**
Can be solved by running `npm i @ngx-tonysamperi/dom --save`

**To Reproduce**
- Run `npm install @popperjs/core ngx-popperjs --save` 
- Either:
  - Check node_modules: No `@ngx-tonysamperi/dom` available
  - Consume `NgxPopperjsModule` anywhere in your app

**Expected behavior**
`ngx-tonysamperi/dom` should be installed as dependency as well when running `npm install @popperjs/core ngx-popperjs --save`

**Versions**
 - ngx-popperjs [14.0.0]
 - @angular/core version [14.0.3]
 - @angular/material version [14.0.3]
 - typescript version [4.7.4]

**Additional context**
Seems like I'm the only one with this issue, maybe there is something that I'm missing?

**Comment by tonysamperi** [comment]
Before dom there was smp-core-utils and it's never been marked as dependency, or peer.

**Comment by tonysamperi** [comment]
Actually after a second though, smp-core-utils wasn't used, that's why it wasn't a peer. Ok, I'll patch it right away!

**Comment by tonysamperi** [comment]
@habtim 

I moved `@ngx-tonysamperi/dom` and `@popperjs/core` to dependencies, so that installing `ngx-popperjs` will automatically get everything!

v 13.3.0
