### ISSUE TITLE
Warning: Entry point 'ngx-popperjs' contains deep imports

### ISSUE THREAD

**Issue by DerZyklop** [tonysamperi/ngx-popperjs#3]
ngcc gives me this warning:

Warning: Entry point 'ngx-popperjs' contains deep imports into '/Users/nils/S/plano/scheduler.frontend.ng2/node_modules/@popperjs/core/lib/types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

[Someone somewhere](https://github.com/angular/angular/issues/35615#issuecomment-590558673) said:
_It is not possible for ngcc to know whether the deep imports are going to be problematic or not, so it is reasonable to give the developer this information so that they can make a decision for themselves._

Thanks for this project 💚

**Comment by tonysamperi** [comment]
@DerZyklop thank you! I noticed that warning, but luckily it doesn't cause any issues at the moment.
A possible alternative would be replicating the models, so we don't need to do the *deep imports*. 
But I have a repulsion for "replicate"...so...I'll keep this way until it's really a problem :)
