### ISSUE TITLE
BUG: takeUntil export was not found in 'rxjs'

### ISSUE THREAD

**Issue by MartinRios23** [tonysamperi/ngx-popperjs#32]
**NOTE**

**Describe the bug**
I installed the 13.3.0 version of ngx-popperjs And when I try to import the module, when compiling I get the following error:

./node_modules/@ngx-tonysamperi/dom/fesm2015/ngx-tonysamperi-dom.mjs:27:14-19 - Error: export 'first' (imported as 'first') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

AND

./node_modules/ngx-popperjs/fesm2015/ngx-popperjs.mjs:660:66-75 - Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

1. Install npm install @popperjs/core ngx-popperjs --save
2. Then install npm i ngx-popperjs@13.3.0
3. Import NgxPopperjsModule in some module
4. See error during compilation

**Screenshots**
![image](https://user-images.githubusercontent.com/62347890/199043810-825d8a31-ca88-44bc-a590-f9a903144900.png)
![Captura de pantalla 2022-10-31 a la(s) 12 27 22](https://user-images.githubusercontent.com/62347890/199045732-3ce0e0f9-78c8-4df1-b092-a279948830ee.png)

**Desktop (if execution):**
 - OS: MacOS
 - Browser: chrome

** Versions
 - ngx-popperjs version: 13.3.0
 - @angular/core version: 13.3.11
 - @angular/material version 13.3.9
 - typescript version: 4.6.4

**Question
This may be happening because takeUntil is being used from 'rxjs' instead of 'rxjs/operators'?. I tried all 13.x version andI can't get the dependency to work properly. It always gives error when compiling

**Comment by tonysamperi** [comment]
You think that I made this library and could ever import stuff from the wrong place?
Show me your `package.json` please

**Comment by MartinRios23** [comment]
{
    "name": "@fuse/starter",
    "version": "13.6.0",
    "description": "Fuse - Angular Admin Template and Starter Project",
    "author": "https://themeforest.net/user/srcn",
    "license": "https://themeforest.net/licenses/standard",
    "private": true,
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "start:local": "ng serve --configuration local",
        "start:develop": "ng serve --configuration develop",
        "start:release": "ng serve --configuration release",
        "start:prod": "ng serve --configuration production",
        "build:local": "ng build --configuration local",
        "build:develop": "ng build --configuration develop",
        "build:release": "ng build --configuration release",
        "build:prod": "ng build --configuration production",
        "build": "ng build",
        "watch": "ng build --watch --configuration development",
        "test": "ng test",
        "lint": "ng lint",
        "sonar": "sonar-scanner"
    },
    "dependencies": {
        "@angular/animations": "13.3.11",
        "@angular/cdk": "13.3.9",
        "@angular/common": "13.3.11",
        "@angular/compiler": "13.3.11",
        "@angular/core": "13.3.11",
        "@angular/forms": "13.3.11",
        "@angular/material": "13.3.9",
        "@angular/material-moment-adapter": "13.3.9",
        "@angular/platform-browser": "13.3.11",
        "@angular/platform-browser-dynamic": "13.3.11",
        "@angular/router": "13.3.11",
        "@dicebear/avatars": "^4.10.0",
        "@dicebear/avatars-jdenticon-sprites": "^4.10.0",
        "@fortawesome/angular-fontawesome": "^0.10.1",
        "@fortawesome/fontawesome-svg-core": "^1.3.0",
        "@fortawesome/free-solid-svg-icons": "^6.0.0",
        "@ng-select/ng-select": "^8.3.0",
        "@ngneat/transloco": "2.22.0",
        "@ngx-translate/core": "^13.0.0",
        "@ngx-translate/http-loader": "^6.0.0",
        "@ngxs/storage-plugin": "^3.7.2",
        "@ngxs/store": "^3.7.2",
        "@popperjs/core": "^2.11.6",
        "apexcharts": "^3.29.0",
        "crypto-js": "3.3.0",
        "file-saver": "^2.0.5",
        "highlight.js": "11.2.0",
        "highlightjs-line-numbers.js": "^2.8.0",
        "lodash-es": "4.17.21",
        "moment": "^2.29.1",
        "ng-apexcharts": "^1.5.12",
        "ngx-highlightjs": "^5.0.0",
        "ngx-markdown": "^13.1.0",
        "ngx-mask": "^8.1.7",
        "ngx-popperjs": "^13.3.0",
        "ngx-print": "^1.2.1",
        "ngxs-reset-plugin": "^2.0.0",
        "perfect-scrollbar": "1.5.2",
        "rrule": "2.6.8",
        "rxjs": "6.6.7",
        "tslib": "2.3.1",
        "zone.js": "0.11.4"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^13.3.9",
        "@angular-eslint/builder": "^13.5.0",
        "@angular-eslint/eslint-plugin": "^13.5.0",
        "@angular-eslint/eslint-plugin-template": "^13.5.0",
        "@angular-eslint/schematics": "^13.5.0",
        "@angular-eslint/template-parser": "^13.5.0",
        "@angular/cli": "13.3.9",
        "@angular/compiler-cli": "13.3.11",
        "@angular/localize": "^13.3.11",
        "@ngxs/devtools-plugin": "^3.7.2",
        "@tailwindcss/aspect-ratio": "0.2.1",
        "@tailwindcss/line-clamp": "0.2.1",
        "@tailwindcss/typography": "0.4.1",
        "@types/chroma-js": "2.1.3",
        "@types/crypto-js": "3.1.47",
        "@types/file-saver": "^2.0.4",
        "@types/highlight.js": "10.1.0",
        "@types/jasmine": "3.8.2",
        "@types/lodash": "4.14.172",
        "@types/lodash-es": "4.17.4",
        "@types/node": "12.20.21",
        "@typescript-eslint/eslint-plugin": "4.30.0",
        "@typescript-eslint/parser": "4.30.0",
        "autoprefixer": "10.3.3",
        "chroma-js": "2.1.2",
        "eslint": "7.32.0",
        "eslint-plugin-import": "2.24.2",
        "eslint-plugin-jsdoc": "36.0.8",
        "eslint-plugin-prefer-arrow": "1.2.3",
        "jasmine-core": "3.8.0",
        "karma": "^6.4.1",
        "karma-chrome-launcher": "3.1.0",
        "karma-coverage": "2.0.3",
        "karma-jasmine": "4.0.1",
        "karma-jasmine-html-reporter": "1.7.0",
        "lodash": "4.17.21",
        "postcss": "8.3.6",
        "sonar-scanner": "^3.1.0",
        "tailwindcss": "2.2.9",
        "typescript": "4.6.4"
    }
}

Here's the package.json!

**Comment by tonysamperi** [comment]
![image](https://user-images.githubusercontent.com/5957244/199069865-8fa2e3ff-85e3-4fa5-a403-117e79c680d2.png)

Bye

**Comment by MartinRios23** [comment]
Should I upgrade my version of RXJS? Which would be the recommended one?

**Comment by tonysamperi** [comment]
`"rxjs": "^7.4.0"`

I'll add this to the peer deps so that NPM will show at least a warning when using an older version!

**Comment by MartinRios23** [comment]
Thanks! I'll try this now!
