### ISSUE TITLE
Strange text wrapping happening

### ISSUE THREAD

**Issue by jamesnewportbeach** [tonysamperi/ngx-popperjs#39]
Thanks for making this component! I'm trying out the basics and the words wrap - just adding this:

[popper]="Delete"
[popperTrigger]="'hover'"

'Delete' wraps between the 'l' and the 'e' - should I be setting a width somehow or overriding some class? I don't think you should be setting word-wrap here at all

It's like it's squishing the size down to the minimum size - I tried applying word-wrap: normal, and that didn't work, and applying minimum width wont work because it will just start wrapping within-word at whatever minimum I set - I was hoping it would shrink/grow to the maximum size, then wrap at the word - not-within the word...

div.ngxp__container {
    background: #000;
    color: white;
    font-size: 11px;
    border: 0;
    max-width: 250px;
    box-shadow: 0 3px 5px -1px rgba(0, 0, 0, 0.2), 0 5px 8px 0 rgba(0, 0, 0, 0.14),
        0 1px 14px 0 rgba(0, 0, 0, 0.12);
    z-index: 999;
    word-wrap: normal;
    text-align: center;

    > .ngxp__arrow:before {
        background-color: #000;
    }
}

**Comment by tonysamperi** [comment]
@jamesnewportbeach I understood the problem only partially...next time remember to create a Blitz with the problem.
Anyway I don't remember but I guess it's to keep the popper at minimum size and most importantly avoid words exceeding the popper, cause with poppers being small it's very easy to overflow...
But yeah, if in your case a normal wrap doesn't cause issues, you can definitely override it.
Cheers.
