### ISSUE TITLE
BUG: when popup opened programatticaly click outside does not work

### ISSUE THREAD

**Issue by hheexx** [tonysamperi/ngx-popperjs#40]
When I open popup manually using content.show() click outside logic does not work so I have to add my own.....

**Comment by tonysamperi** [comment]
Nope, I specifically solved this bug some time ago...
Please have a better look at your code and most importantly create a Blitz to reproduce the issue.

**Comment by hheexx** [comment]
Here is calling code:

`    <input type="text" class="form-control" placeholder="Search..." [ngModel]="searchQuery"
            (ngModelChange)="queryUpdated.next($event)" [popper]="searchDropdown"
            [popperPlacement]="util.popperPlacement.BOTTOMSTART" [popperTrigger]="util.popperTriggers.none"
            (click)="queryUpdated.next(searchQuery)">`

(click) triggers .show()
this code does not work

if I change [popperTrigger] to click then it works.
