### ISSUE TITLE
QUESTION: How to disable default flipping of the popper

### ISSUE THREAD

**Issue by pavandixit93** [tonysamperi/ngx-popperjs#44]
**Describe the bug**
How to disable default flipping? I have set enabled as false for flip config inside `app.component.ts` but the popper is flipped when user scrolls the page. In the old version of ngx-popper it used to disable flip when enabled is set false for flip config.
Is it possible to disable the flipping without setting `placement` input? if yes please share the config/guidance if available.

_Note: If I set `popperPlacement='top'` manually, this disables default flipping but this will need change at multiple files if we want to upgrade to ngx-popperjs, I confirmed that, placement change is not required in core library but required in wrapper_

**Steps to reproduce the behavior:**
1. Go to 'https://stackblitz.com/edit/popperjs-flip-issue?file=src%2Fapp%2Fapp.component.html'
2. Click on `Click me` div element, You will see popper placed above the popper trigger element
3. Scroll the page using body scrollbar
4. Notice that popper is flipped to the bottom of the popper trigger element

**Expected behavior**
When I set `enabled as false` for flip config it should not flip the popper on scrolling the main page. In some cases we dont want to flip select box/dropdown which is popper.

**Screenshots**

**Desktop (if execution):**

** Versions
 - ngx-popperjs version [e.g. 10.0.4]
 - @angular/core version [e.g. 10.2.5]
 - typescript version [es. 3.9.2]

**Additional context (optional)**

**Additional context**

**Comment by tonysamperi** [comment]
Hello @pavandixit93 you need to create a modifier!
See https://popper.js.org/docs/v2/modifiers/#name
