### ISSUE TITLE
HELP:  Unable to install ngx-popperjs since ngx-ui-tour-core is present inside project.

### ISSUE THREAD

**Issue by pavandixit93** [tonysamperi/ngx-popperjs#45]
Hi @tonysamperi I have removed other static descriptions and sorry about that. Here is the error that I am getting, I understood from the error but since `ngx-ui-tour-core` is heavily used and was working with `ngx-popper` earlier how can we fix this? is there any alternative way to fix this instead of using `ngx-tour-wizard`?
**Error: Unfortunately ngx-popperjs is not compatible with ngx-ui-tour-core!**
We are planning to remove `ngx-popper` and use `ngx-popperjs` but getting this error.
Could you please mention reason behind it?

![image](https://user-images.githubusercontent.com/21095558/230879932-f6863b4a-d5d1-40fb-bc34-1c17808c5c73.png)

**Comment by tonysamperi** [comment]
@pavandixit93 yes I can explain!

**Comment by pavandixit93** [comment]
Hi @tonysamperi Could you please explain it? So that we will add the same inside Notes section and will try this upgrade in the future by alongwith by removing `ngx-ui-tour-core` and by adding `ngx-tour-wizard`.

**Comment by tonysamperi** [comment]
@pavandixit93 that before was a hint that I don't have time to explain! 😂
Unfortunately this is the situation. 

Cheers!

**Comment by sonikasharma1403** [comment]
@tonysamperi

I am also facing a similar issue. I know you don't have the time to explain the issue, but it would really help us if you could give us an explanation as to why the library won't work with `ngx-ui-tour-core`. 

can we skip the post-install check via some flag? 

PS: Thank you for creating such an awesome open-source library.
