### ISSUE TITLE
Popper attributes not working in template

### ISSUE THREAD

**Issue by bgreay** [tonysamperi/ngx-popperjs#46]
**Describe the bug**
When trying to use popper in a template the, attributes (such as placement) of ngx-popperjs cause error, for example:

`Error: src/app/views/test.component.html:62:17 - error TS2322: Type '"right-start"' is not assignable to type 'NgxPopperjsPlacements'.`

**To Reproduce**
See error here
https://stackblitz.com/edit/angular-245fwh?file=src%2Fmain.ts

Note that the stackblitz uses Angular 15.2.7 but I can also reproduce on 15.0.0

**Expected behavior**
Can use attributes without error

**Additional context**
I think the strictTemplates property in `tsconfig.json / angularCompilerOptions` default to true in Angular 15. 
If you change to false and restart ng server there are no template errors regarding ngx-popperjs

**Workaround**
Disable strict templates in `tsconfig.json`, or
as the stackblitz shows you can work around this by importing the attributes you wish to use and export to template

```
import { NgxPopperjsTriggers, NgxPopperjsPlacements } from 'ngx-popperjs';

export class App {
  triggers = NgxPopperjsTriggers;
  placements = NgxPopperjsPlacements;
}

... and in the template...

    [popperTrigger]="triggers.hover"
    [popperPlacement]="placements.BOTTOM">
```

**Versions**
 - ngx-popperjs version [15.0.4]
 - @popperjs/core version [2.11.7]
 - @angular/core version [15.x.x]
 - typescript version [es. 4.8.2]

**Comment by tonysamperi** [comment]
I don't see why opening an issue if you already knew the reason...
