### ISSUE TITLE
TS2322: Type '"click"' is not assignable to type 'NgxPopperjsTriggers'

### ISSUE THREAD

**Issue by madmacc** [tonysamperi/ngx-popperjs#51]
**Describe the bug**
When using ng serve for Angular 16 I get the following build error:
`TS2322: Type '"click"' is not assignable to type 'NgxPopperjsTriggers'`
It was working fine in my Angular 10 project but this error only occurs in a new Angular 16 project.

1. Create a new Angular 16 project.
2. Install following instructions e.g. npm i ngx-popperjs add to app module etc
3. Add the following HTML `<i id="instructions" class="fa-solid fa-circle-info item-info" [popper]="getInstructions(item)" [popperTrigger]="'click'" matTooltip="Click for instructions"></i>`

![image](https://github.com/tonysamperi/ngx-popperjs/assets/43654472/b94521b5-bbe6-4660-a257-7eecb28796b7)

**Expected behavior**
Popper should work as it does in the Angular 10 project

** Versions
 - ngx-popperjs version 16.0.0
 - @popperjs/core 2.11.8
 - @angular/core version 16.0.0
 - @angular/material version 16.0.3
 - typescript version 5.0.2

**Additional context**
Seems someone else had the same issue: https://github.com/tonysamperi/ngx-popperjs/issues/23

**Comment by tonysamperi** [comment]
Search the issues
