### ISSUE TITLE
Chrome Version 115.0.5790.102 seems to have broken positioning

### ISSUE THREAD

**Issue by KalliMan** [tonysamperi/ngx-popperjs#52]
After upgrade to the latest chrome, the popper positionning does not work correctly enymore. 

The easiest way to reproduce the problem is using the supplied examples:
https://tonysamperi.github.io/ngx-popperjs/

It is reproducible at least on " OVERFLOW PREVENTION", "OPEN ON CLICK", "OPEN ON CLICK + CLOSE ON SCROLL" examples. What is interesting that scrolling fixes the position of the popper.

Note: The same issue is reported for the ngx-popper:
https://github.com/MrFrankel/ngx-popper/issues/180

**Comment by gertot** [comment]
it seems that
`popper-content {
    position: unset!important;
    display: unset!important;
}`
may help

**Comment by tonysamperi** [comment]
I'm removing a few comments with weird CSS solutions, because mostly they don't work at all.
I'm working at the fix but it's not simple.

**Comment by KalliMan** [comment]
> it seems that
> 
> ```css
> popper-content {
>     position: unset!important;
>     display: unset!important;
> }
> ```
> 
> may help

It does not help unfortunately. 

However this suggestion seems to work.
https://github.com/MrFrankel/ngx-popper/issues/180#issuecomment-1651561956

**Comment by gertot** [comment]
> > it seems that
> > ```css
> > popper-content {
> >     position: unset!important;
> >     display: unset!important;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > may help
> 
> It does not help unfortunately.
> 
> However this suggestion seems to work. [MrFrankel/ngx-popper#180 (comment)](https://github.com/MrFrankel/ngx-popper/issues/180#issuecomment-1651561956)

It belongs to the version you use!

**Comment by muneeb26** [comment]
Hey @tonysamperi do you know when there will an official fix released for this?

**Comment by tonysamperi** [comment]
@muneeb26 hi, I should be able to release something at least for v16 this week!

**Comment by AdamsContreras999** [comment]
great Mr we would be grateful for this solution @tonysamperi

**Comment by serhiisol** [comment]
Seems like 
```css
.ngxp__container {
  display: block !important;
}
```
does the trick.

**Comment by tonysamperi** [comment]
@serhiisol that's not a fix though. There's a reason if the "display: block" is set by the js and it's not in css!

**Comment by serhiisol** [comment]
Well, at least that solves the problem for now. I've checked a bunch of scenarios and they seem to work correctly.

**Comment by tonysamperi** [comment]
@serhiisol this is what I'm talking about. If it's not visible (opacity) but not hidden (block) you won't be able to click "My action".
Also in this specific scenario, a part of the popper covers the trigger, so if I click there, the popper won't show!

![image](https://github.com/tonysamperi/ngx-popperjs/assets/5957244/693f9ad8-5805-44a2-a300-739929b2db19)

**Comment by tonysamperi** [comment]
Yeah, but that I don't like as well, because in a first instance the popper is shown somewhere and when you recalculate it moves...
I think I got the right solution though...
Keep you posted

**Comment by serhiisol** [comment]
It shouldn't be a problem for the case if appendTo set to body.

**Comment by tonysamperi** [comment]
> It shouldn't be a problem for the case if appendTo set to body. @tonysamperi do you need help with the solution?

No, don't worry I'll figure this out.
Btw in v17 I could be migrating to the new floating UI lib...

Cheers

**Comment by serhiisol** [comment]
@tonysamperi what do you think if we replace toggle of display property with visibility?

https://github.com/tonysamperi/ngx-popperjs/assets/8107129/cce60b50-6491-4157-a12c-bb230f5e92d6

**Comment by tonysamperi** [comment]
> @tonysamperi what do you think if we replace toggle of display property with visibility?
> 
>  Screen.Recording.2023-08-02.at.9.21.38.PM.mov

@serhiisol same issues as above...

**Comment by serhiisol** [comment]
It's not. The element is there but it's not blocking any interactions.

**Comment by tonysamperi** [comment]
@serhiisol I've been doing this stuff for 20 years. Visibility hidden doesn't let mouse interactions go through. Then I should add another css porkaround like `pointer-events: none`.

**Comment by serhiisol** [comment]
It seems to work just fine...

https://github.com/tonysamperi/ngx-popperjs/assets/8107129/fa4347bf-eecf-4801-bf8f-46c37df91c14

**Comment by zanaBizz** [comment]
@tonysamperi Is the fix also going to be backported to v15 for users who haven't yet migrated to using Angular v16?

**Comment by tonysamperi** [comment]
@zanaBizz yes. I was waiting to see if it was stable on v16. Right choice, since there was a teeny tiny bug.
Should publish v15 and v14 and v13 in a few hours...I'm also going to check how many usages of v12 still there...

**Comment by YevheniiPuzyrenko** [comment]
Hi, @tonysamperi !
is the fix gonna be ported to v13 also ?

**Comment by tonysamperi** [comment]
> Hi, @tonysamperi ! is the fix gonna be ported to v13 also ?

Yes! Later today!

**Comment by serhiiuq** [comment]
The issue also happens when `popperAppendTo="body"` is specified on the first event. Note: happens with the latest update.

**Comment by tonysamperi** [comment]
Ok everybody. I figured the real fix. I was so close, but I didn't consider I needed to skip a frame.
I'm reverting to the 16.0.1 and applying the real fix (with v 16.0.6 and of course the v 15 14 and 13)

Thanks @solo-unitq because I got that to fix the "append to body".

**Comment by AdamsContreras999** [comment]
> Bien, todos. Me di cuenta de la solución real. Estaba tan cerca, pero no consideré que necesitaba saltarme un cuadro. Estoy volviendo a la versión 16.0.1 y aplicando la solución real (con la versión 16.0.6 y, por supuesto, la versión 15, 14 y 13)
> 
> Gracias@solo-unitqporque obtuve eso para arreglar el "agregar al cuerpo".

please man ! awesome!

**Comment by kundralaci** [comment]
> Ok everybody. I figured the real fix. I was so close, but I didn't consider I needed to skip a frame. I'm reverting to the 16.0.1 and applying the real fix (with v 16.0.6 and of course the v 15 14 and 13)
> 
> Thanks @solo-unitq because I got that to fix the "append to body".

Thank you very much for hunting down this bug! Can you please also port it back to the 12 version? (Yes, I know we really need to update, but it's not my decision, unfortunately... thank you again!)

**Comment by EdoMagen** [comment]
Thank you @tonysamperi !

**Comment by tonysamperi** [comment]
Hi all, released the new versions for v16, 15 and 14. Tomorrow 13 and 12.

**Comment by AdamsContreras999** [comment]
this change 16.0.6 still shows incorrectly when a popper is opened from the click event it shows the popper at a different address from where it was clicked. 
@tonysamperi

**Comment by tonysamperi** [comment]
> this change 16.0.6 still shows incorrectly when a popper is opened from the click event it shows the popper at a different address from where it was clicked. @tonysamperi

mmm no, not to me. 
Are you trying here? https://tonysamperi.github.io/ngx-popperjs/

**Comment by AdamsContreras999** [comment]
> > this change 16.0.6 still shows incorrectly when a popper is opened from the click event it shows the popper at a different address from where it was clicked. @tonysamperi
> 
> @AdamsContreras999 mmm no, not to me. Are you trying here? https://tonysamperi.github.io/ngx-popperjs/

apply a popper in an angular modal and you will see if the bug is seen.

@tonysamperi

**Comment by tonysamperi** [comment]
> 

@AdamsContreras999 man I can't replicate all the world cases, if you create a blitz with the issue, I can take a look.
Also "Angular modal" is too generic.

**Comment by tonysamperi** [comment]
Released v 13 and 12!

**Comment by aleksander351** [comment]
> > It shouldn't be a problem for the case if appendTo set to body. @tonysamperi do you need help with the solution?
> 
> No, don't worry I'll figure this out. Btw in v17 I could be migrating to the new floating UI lib...
> 
> Cheers

@tonysamperi 
After updating to the latest version, sometimes the vertical position is still not calculated correctly. It occurs on Edge as well as on Chrome browsers.
I.e. the y value after the first click is 397, whereas on the second try it's 257, which is correct.

![position-1](https://github.com/tonysamperi/ngx-popperjs/assets/7508670/a421883c-ccfa-43f1-97a7-c05fba9d9388)
![position-3](https://github.com/tonysamperi/ngx-popperjs/assets/7508670/cc1f6d1f-df1e-4f0d-81b3-8e8db9ed7bcb)

**Comment by tonysamperi** [comment]
@aleksander351 please create a blitz reproducing the problem and report all the info, including OS, RAM, etc.

**Comment by ahmedataulkareem** [comment]
I am facing the same issue as @aleksander351. It renders the pop-up correctly but sometimes doesn't calculate the vertical length properly which results in rendering the pop-up at the wrong place. Facing this issue with Angular v14 and ngx-popperjs v14.1.8

![image](https://github.com/tonysamperi/ngx-popperjs/assets/65401088/01e83c21-4db2-4ca8-b7d0-8136856a5c9c)
![image](https://github.com/tonysamperi/ngx-popperjs/assets/65401088/a4f03d32-f498-4fc0-b105-d8e3664be065)


Added the s.s for the following when the error reoccurs

**Comment by tonysamperi** [comment]
@ahmedataulkareem man, same reply as aleksander...please create a blitz!

**Comment by aleksander351** [comment]
> @ahmedataulkareem man, same reply as aleksander...please create a blitz!

we solved it with the position: unset; workaround for now.
