### ISSUE TITLE
BUG: v16 introduces small dot

### ISSUE THREAD

**Issue by bersling** [tonysamperi/ngx-popperjs#54]
**Describe the bug**
v16 introduces a small dot that I don't think is supposed to be there. The ngxp__container class seems to be responsible for it.

**To Reproduce**

Stackblitz: https://stackblitz.com/edit/stackblitz-starters-ntdnfh

Here's a v15 stackblitz, the dot isn't there https://stackblitz.com/edit/stackblitz-starters-yzdkhv 

**Expected behavior**

No dot should appear.

**Screenshots**

<img width="679" alt="Screenshot 2023-08-03 at 10 41 36" src="https://github.com/tonysamperi/ngx-popperjs/assets/10352805/683d5e60-6532-4f31-8ad2-4108b16148da">

I've colored the box shadow of that dot in red so it can be seen better. The box shadow was already there however.

**Desktop (if execution):**
 - OS: Tested on Mac
 - Browser: Tested on Firefox, Chrome

**Versions**
 - ngx-popperjs version: 16.0.2
 - @angular/core version: 16.1.7
 - @angular/material version: -
 - typescript version: -

**Additional Context**

I also get a small white not fully closed popper-window in an app I have that uses ngx-popper since v16, however not in the stackblitz. I'll need to dig a bit deeper to reproduce that in the stackblitz though. I thought to give that context information here since (a) maybe it's related, (b) even if not, you might immediately know what's the problem.

![Screenshot 2023-08-03 at 10 57 02](https://github.com/tonysamperi/ngx-popperjs/assets/10352805/42baa6f6-82b3-4f0c-926f-b8436d728357)

**Comment by KikoCosmetics** [comment]
Yeah it's caused by the workaound to the Chrome browser.
I'll remove the border when hidden.
In the meantime you can do 

```
.ngxp__container.ngxp__hide {
    border: 0;
}
```

Cheers
