### ISSUE TITLE
BUG: Console log when clicked to open popper ´DOCUMENT CLICK´

### ISSUE THREAD

**Issue by AdamsContreras999** [tonysamperi/ngx-popperjs#57]
version 16.0.4

when open popper and clicked outside the popper show in console the browser ´DOCUMENT CLICK´
![image](https://github.com/tonysamperi/ngx-popperjs/assets/90850547/4e0e7f7c-3a38-4d11-8286-0b5b526d2e38)

**Comment by tonysamperi** [comment]
Yeah I was debugging the tests...I figured I forgot to remove it...
I will remove it as soon as I fix the tests.
Thanks for reporting.
