### ISSUE TITLE
BUG: when setting the style to min-height or min-width in the popperStyles property the popper is opened at once without calling the click event

### ISSUE THREAD

**Issue by AdamsContreras999** [tonysamperi/ngx-popperjs#58]
version 16.0.4
when setting the style to min-height or min-width in the popperStyles property the popper is opened at once without calling the click event

check this example please
https://stackblitz.com/edit/stackblitz-starters-4y8lgy?file=package.json,src%2Fmypopper%2Fmypopper.component.ts

![image](https://github.com/tonysamperi/ngx-popperjs/assets/90850547/160cb3f1-cc85-4016-963d-d8e2f31a443a)
![image](https://github.com/tonysamperi/ngx-popperjs/assets/90850547/697e3b5f-06d6-4f7c-b6e6-59096687f312)

**Comment by tonysamperi** [comment]
Why would you set min-width and min-height that way?
Just use CSS. 
I know that applied styles override the CSS. 
I can't set a default for every CSS property.
There's no choice right now, due to the Chrome bug.

**Comment by bersling** [comment]
But do you really have to apply the `popperStyles` and the `popperApplyClass` when the popup is closed? Can you not conditionally only apply those when the popup is shown? Would that not solve all the problems we're having now?

**Comment by tonysamperi** [comment]
> But do you really have to apply the `popperStyles` and the `popperApplyClass` when the popup is closed? Can you not conditionally only apply those when the popup is shown? Would that not solve all the problems we're having now?

No it wouldn't solve anything and it would risk introducing more regressions. Plus it would degrade the performance if I added conditionals on everything.
