### ISSUE TITLE
Fix for "Types are not assignable to defined types" BUG

### ISSUE THREAD

**Issue by jigneshk5** [tonysamperi/ngx-popperjs#62]
Hi,
I wanted to save some time for people who wanted to use this library v 15.2.0 . Issue #23 is genuine and can be faced by anyone.

**Documentation mistake:**
Everywhere in the examples **popperTrigger** is mentioned to use like this:
```HTML  
   <popper-content #popper1Content>
       <p class="bold">Popper on bottom</p>
   </popper-content>
   <div [popper]="popper1Content"
        [popperShowOnStart]="true"
        [popperTrigger]="'click'"
        [popperHideOnClickOutside]="true"
        [popperHideOnScroll]="true"
        [popperPlacement]="'bottom'">
       <p class="bold">Hey!</p>
       <p class="thin">Choose where to put your popper!</p>         
   </div>
  ```
And we will get following issue with this:
![Screenshot 2023-09-18 010652](https://github.com/tonysamperi/ngx-popperjs/assets/36167650/6bdb421f-ed18-4e55-91f7-c2e2935c5704)

**How I solved it:**

In TS file:
import {NgxPopperjsTriggers,NgxPopperjsPlacements} from "ngx-popperjs";
trigger= NgxPopperjsTriggers.hover
placement= NgxPopperjsPlacements.AUTO

In Html File:
```HTML  
   <popper-content #popper1Content>
       <p class="bold">Popper on bottom</p>
   </popper-content>
   <div [popper]="popper1Content"
        [popperShowOnStart]="true"
        [popperTrigger]="trigger"
        [popperHideOnClickOutside]="true"
        [popperHideOnScroll]="true"
        [popperPlacement]="placement">
       <p class="bold">Hey!</p>
       <p class="thin">Choose where to put your popper!</p>         
   </div>
  ```
Thank you & Cheers!

**Comment by tonysamperi** [comment]
@jigneshk5 nope man you're totally off.

1) It's a problem of how you configure Angular...go read the docs.
2) I created the "popperLoose" directive to deal with all of you guys who really can't deal with writing code the way it should be.

**Comment by tonysamperi** [comment]
@jigneshk5 also read my reply in #23...maybe you can get the hint and fix your code.
