### ISSUE TITLE
rxjs 'takeUntil' import incorrect when using wrong rxjs versions (lower than 7.1.0)

### ISSUE THREAD

**Issue by johndoe246** [tonysamperi/ngx-popperjs#63]
**NOTE**
I was using 12.2.1 version. It was working fine until couple of months but now I have observed positioning of the tooltip is not correct. So I tried updating it to higher versions (12.2.2). 
- It looks like you are using rxjs in the commit (050ca6bb1e05305ffadeb1c81b9642e23018f9f1)
- You are using old rxjs importing style to import 'takeUntil' operator
- It is giving me compile time error saying 'takeUntil' was not found in 'rxjs'
- I have tried updating from `import { takeUntil } from "rxjs"` to `import { takeUntil } from "rxjs/operators"`
- After this update everything is working fine
- Can you make this change and release 12.2.3 version may be
- This is very urgent can you please do this change ASAP

**Expected behavior**
Instead of `import { takeUntil } from "rxjs"` use **`import { takeUntil } from "rxjs/operators"`**

**Screenshots**
![image](https://github.com/tonysamperi/ngx-popperjs/assets/144712737/223d6e38-d20d-41a8-b399-49ec130ebc91)

** Versions
 - ngx-popperjs version [12.2.2]
 - @popperjs/core: ^2.11.5
 - @angular/core version ^12.3.0
 - rxjs ~6.6.0
 -

**Comment by tonysamperi** [comment]
Man, this library has never been compatible with rxjs < 7

**Comment by tonysamperi** [comment]
I actually see that rxjs is not in the peerDependencies in v12...I must have added at some point...(I mean adding the peer depencency in the library package...I guess some point in v13).

I'll make a quick patch to add it.

Then you'll get a warning from npm that you should update your version of rxjs.

**Comment by kartik468** [comment]
Yes you have added it in the 12.2.2 commit itself. Not sure if I can update the rxjs version. That will be major change. Since in the new rxjs version both import styles are supported. Can you please update the import like I said in the bug.
That will save me a lot of trouble.

**Comment by tonysamperi** [comment]
@kartik468 I already committed and published the peerDependency.
The problem is yours: Angular 12 had rxjs v7 as dependency. Why you kept v6?
It's just a coincidence that you haven't had any problems with libraries so far.
You have to update to v7. I can assure you that there are minimal differences, just a few operators were deprecated or changed signature.
Not a big work and you would have then the right version to work with Angular 12.

**Comment by kartik468** [comment]
Rxjs v6 came with angular 12. https://angular.jp/guide/versions

And I am not in position to update it now

**Comment by tonysamperi** [comment]
I'm not in the position to downgrade, your alternative is downgrading to the previous version of ngx-popperjs!

**Comment by kartik468** [comment]
> @kartik468 I already committed and published the peerDependency.
> The problem is yours: Angular 12 had rxjs v7 as dependency. Why you kept v6?
> It's just a coincidence that you haven't had any problems with libraries so far.
> You have to update to v7. I can assure you that there are minimal differences, just a few operators were deprecated or changed signature.
> Not a big work and you would have then the right version to work with Angular 12.
> 

It's a huge project and we are in the middle of the release. We can't update it now

**Comment by tonysamperi** [comment]
> > @kartik468 I already committed and published the peerDependency.
> > The problem is yours: Angular 12 had rxjs v7 as dependency. Why you kept v6?
> > It's just a coincidence that you haven't had any problems with libraries so far.
> > You have to update to v7. I can assure you that there are minimal differences, just a few operators were deprecated or changed signature.
> > Not a big work and you would have then the right version to work with Angular 12.
> 
> It's a huge project and we are in the middle of the release. We can't update it now

Then I suggest you to download the source, change that piece code, build the package and install the tgz manually in your project.
Again, not a big work.

**Comment by tonysamperi** [comment]
@kartik468 here. Just unzip this to your project root, then run `npm i ngx-popperjs-12.2.3.tgz`


[ngx-popperjs-12.2.3.tgz.zip](https://github.com/tonysamperi/ngx-popperjs/files/12708270/ngx-popperjs-12.2.3.tgz.zip)

**Comment by kartik468** [comment]
> @kartik468 I already committed and published the peerDependency.
> The problem is yours: Angular 12 had rxjs v7 as dependency. Why you kept v6?
> It's just a coincidence that you haven't had any problems with libraries so far.
> You have to update to v7. I can assure you that there are minimal differences, just a few operators were deprecated or changed signature.
> Not a big work and you would have then the right version to work with Angular 12.
> 

I think Rxjs v6 came with angular 12. See https://angular.jp/guide/versions


And regarding local update. We have different build process. I think I can not do these changes. I will try but I don't think this is possible

**Comment by tonysamperi** [comment]
@kartik468  I looked at the link, and Angular 12.2 had rxjs 6 or 7, but that was just an excuse for updating. 
Any library you download from the web don't have to stick with that version, they can even use 8 if you want.

Wait a sec, maybe I have the best solution that let's you keep both versions independently. I'm setting up a stackblitz.

**Comment by tonysamperi** [comment]
@kartik468 ok I surrender. Published 12.2.4 with the changed import.

Cheers

**Comment by KrishnakantP** [comment]
Thanks @tonysamperi
