### ISSUE TITLE
BUG: Override defaults not working for Angular 16 Standalone Bootstrap

### ISSUE THREAD

**Issue by SleeplessFox** [tonysamperi/ngx-popperjs#64]
**Describe the bug**
Im tried to use ngx-popperjs with an angular 16 project with just standalone components and bootsrapping a standalone component. 
Unfortunatelly it seems that the overriding of the default parameters has no effect AND the default trigger HOVER is also not working. 
I got default "click"

**To Reproduce**
My Main.ts config:

````
bootstrapApplication(AppComponent, {
  providers: [
    importProvidersFrom(
      BrowserModule,
      AppRoutingModule,
      FormsModule,
      ReactiveFormsModule,
      NgxPopperjsModule.forRoot({
        placement: NgxPopperjsPlacements.AUTO,
        applyClass: 'popper-tooltip',
        showDelay: 200,
        trigger: NgxPopperjsTriggers.hover,
      })
    ),
    provideAnimations(),
    provideHttpClient(withInterceptorsFromDi()),
  ],
}).catch((err) => console.error(err));
````

**Expected behavior**
Override trigger with HOVER and popper tooltip will be shown on hover not just on click.

**Desktop (if execution):**
 - OS: Windows
 - Browser chrome

** Versions
 - "ngx-popperjs": "^16.0.6",
 - "@angular/animations": "^16.2.6",
  - "@angular/common": "^16.2.6",
  - "@angular/compiler": "^16.2.6",
  - "@angular/core": "^16.2.6",
  - "@angular/forms": "^16.2.6",
  - "@angular/platform-browser": "^16.2.6",
  - "@angular/platform-browser-dynamic": "^16.2.6",
  - "@angular/router": "^16.2.6",
  -  "typescript": "~4.9.5"

**Comment by tonysamperi** [comment]
@SleeplessFox Can you create a blitz please?

**Comment by tonysamperi** [comment]
@SleeplessFox can you try with the v16.1.0-beta.0? Closing this for now
