### ISSUE TITLE
BUG: not supported enumPopperPlacement.AUTO | AUTOSTART | AUTOEND in version v17

### ISSUE THREAD

**Issue by AdamsContreras999** [tonysamperi/ngx-popperjs#67]
In the new version of ngx-popperjs V17 they removed support for enumPopperPlacement.AUTO | AUTOSTART | AUTOEND 

the ideal is to be able to continue using these properties so that the popper comes out automatically according to the dimensions of the parent element, but in this new version was removed these options, the ideal is that the library continues to support functionality :D

https://github.com/tonysamperi/ngx-popperjs/pull/65/files
![image](https://github.com/tonysamperi/ngx-popperjs/assets/90850547/feb4fe0e-fa82-4855-a966-32e8afdbed8e)

could you please support these properties again for v17 version?

**Comment by tonysamperi** [comment]
I checked floating-ui docs and it can actually be done.
If you want to speed up with a PR, it's welcome.

Cheers

**Comment by tonysamperi** [comment]
PS, not in this repo => this will be implemented in ngx-float-ui to force more people to migrate to that!

**Comment by tonysamperi** [comment]
I came to the conclusion that it simply cannot be implemented, because floating ui will take care of setting the best left position when possibile. See in the screen.
I'm sorry, but unless they add in the library itself the ability to prefer an alignment with the sides of the reference element, this can't be achieved.
What I can do right now would be adding a custom middleware to be the last invoked, to let users have the ultimate control on the popper position. 

![image](https://github.com/tonysamperi/ngx-popperjs/assets/5957244/d587e188-b65b-473c-87df-2507e43453df)

**Comment by AdamsContreras999** [comment]
@tonysamperi If you can add that midleware to be able to take advantage of the functionality that existed in the previous version, it would be of great help to us since we use these libraries and functionalities that are vital for us and it would be great if it continued supporting the alignments enumPopperPlacement.AUTO | AUTOSTART | AUTOEND we would be very satisfied if you can incorporate it sir, thanks in advance

**Comment by tonysamperi** [comment]
@AdamsContreras999 no wait a second, ignore the previous response, I probably found out how to keep it aligned to start or end while also flipping.

**Comment by AdamsContreras999** [comment]
awesome! i'm excited for that! @tonysamperi

**Comment by tonysamperi** [comment]
Damn, this was hard. But it's done. Let me know how it works. 
Personally, I think it's not exactly like it was on popper.js, but it's very close.

**Comment by AdamsContreras999** [comment]
What a pity for the time but reviewing this once again you mention that it has already been resolved? but I see that [popperPlacement]="enumPopperPlacement.AUTO" is not supported in this version 17. Is there still work on another version to implement this? @tonysamperi

**Comment by tonysamperi** [comment]
@AdamsContreras999 as I told you I implemented the auto positioning in ngx-float-ui.
You should migrate to that one!

In this one the AUTO per se doesn't exist. To have auto positioning you just DON'T PASS the position
