### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ilyakonrad** [tonysamperi/ngx-popperjs#68]
1. I've faced a breaking change in version 17, since my code used `popperLoosePlacement="auto"`. Would have been nice to see a "breaking change" warning in the changelog.
2. Is `@floating-ui/dom` really necessary to install considering that it is already a dependency of ngx-popperjs? I've `yarn remove`d `@popperjs/core` and it seems to be working fine.

**Comment by tonysamperi** [comment]
That's not a way to talk. If you can write an issue more respectfully, I will take a look.
