### ISSUE TITLE
Does not work with strictTemplates

### ISSUE THREAD

**Issue by msender** [tonysamperi/ngx-popperjs#8]
**Describe the bug**
We cannot set 'popperTrigger' and 'popperPlacement' as shown in the docs, if we turn on 'strictTemplates' in the angularCompilerOptions.

**Expected behavior**
We should be able to do: `[popperPlacement]="'top'"`

**Screenshots**
![image](https://user-images.githubusercontent.com/8262345/120687294-dfcb7900-c46f-11eb-9196-c50d0c61e9cc.png)

**Additional context**
See here: [https://github.com/angular/angular/issues/35363](url)

**Comment by tonysamperi** [comment]
I don't see why you opened this issue here, if the problem is known to be a core problem. What should I do about it?

**Comment by tonysamperi** [comment]
@Msender also it's an error on your side. If you decide to use strict template checking you should use `NgxPopperjsPlacements` in your controller instead of using directly the string values.

**Comment by msender** [comment]
> I don't see why you opened this issue here, if the problem is known to be a core problem. What should I do about it?

You should update the code to use a union type instead of an enum.

**Comment by tonysamperi** [comment]
> > I don't see why you opened this issue here, if the problem is known to be a core problem. What should I do about it?
> 
> You should update the code to use a union type instead of an enum.

That's not gonna happen. Union type implies hardcoding. 
Enum is way better. 
As I said the problem is on your end and you should use the Enum.
