### ISSUE TITLE
BUG: link broken

### ISSUE THREAD

**Issue by DerZyklop** [tonysamperi/ngx-popperjs#9]
https://tonysamperi.github.io/ngx-popperjs/ has this text in the footer:

_Created with ♥ by Tony Samperi_

Tony Samperi is linked. 

Link leads to https://tonysamperi.github.io/ngx-popperjs/tonysamperi.github.io

Should link to https://tonysamperi.github.io/

✌

**Comment by tonysamperi** [comment]
Ahahah you're right!

**Comment by tonysamperi** [comment]
Fixed, thanks for reporting!
